name: mysql1
version: 0.16.2
description: MySQL driver for Dart
homepage: https://github.com/adamlofts/mysql1_dart

authors:
- James Ots <code@jamesots.com>
- Faisal Abid <faisal.abid@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>
- Adam Lofts <adam.lofts@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  collection: ^1.1.3
  crypto: ">=0.9.2 <3.0.0"
  logging: '>=0.11.1 <0.12.0'
  pool: ^1.3.6

dev_dependencies:
  mockito: ^3.0.0
  options_file:
    git:
      url: https://github.com/ferrerj/optionsfile
      ref: faebe29
  test: ^1.3.0
