name: sqljocky5
version: 1.0.0
description: MySQL driver for Dart
documentation:
homepage: https://github.com/dart-db/sqljocky5

authors:
- James Ots <code@jamesots.com>
- Faisal Abid <faisal.abid@gmail.com>
- Ravi Teja Gudapati <tejainece


environment:
  sdk: '>=1.11.0 <2.0.0'

dependencies:
  collection: ^1.1.3
  crypto: ">=0.9.2 <3.0.0"
  logging: '>=0.11.1 <0.12.0'

dev_dependencies:
  mockito: '>=0.10.1 <0.11.0'
  options_file: '>=0.11.0 <0.12.0'
  test: '>=0.12.3+9 <0.13.0'
